#spring.application.name=log-analysis
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://node01:3306/hive?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true